variables:
  REPO_NAME: git.ucode.space/Phil/goshorly
  DOCKER_BUILDKIT: 1

stages:
- test
- build-binary
- build-docker
- deploy

include:
  - '/.gitlab/ci/always.yml'
  - '/.gitlab/ci/main-branch.yml'
  - '/.gitlab/ci/merge-request.yml'
  - '/.gitlab/ci/tagged-build.yml'
