version: "3"
services:
  web:
    # build: .                  # Only if you want to Build the image on your own Server!
    image: registry.ucode.space/phil/goshorly:latest
    environment:
      - HOST=your_domain_or_ip  # Domain or IP-Adress
      - HTTPS=false             # If you want to use HTTPS
      - PROXY=false             # If you want to use a Reverse Proxy
      - PORT=3000               # The Port you want to use
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - db:/data
    restart: always

volumes:
  db:
