version: "3"
services:
  web:
    # build: .                  # Only if you want to Build the image on your own Server!
    image: nitmali/goshorly:latest
    environment:
      - HOST=2slk.com             # Domain or IP-Adress
      - PORT=3000                   # The Port you want to use
      - HTTPS=true                 # If you want to use HTTPS
      - PROXY=true                 # If you want to use a Reverse Proxy
      - REDIS_URI=redis:6379        # The Redis-URI (name of redis container OOTB)
      - ENABLE_STATS=true           # Enables the /stats public frontend (Default: true)
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - db:/data
    restart: always

volumes:
  db:
