version: "3"
services:
  web:
    # build: . # Only if you want to Build the image on your own Server!
    image: registry.ucode.space/phil/goshorly:latest
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - db:/data
    restart: always

volumes:
  db:
