version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - db:/data
    restart: always

volumes:
  db: