site_name: goshorly docs
site_url: https://2slk.com
repo_url: https://github.com/nitmali/goshorly
site_dir: public
theme:
  name: material
  locale: en
  highlightjs: true

nav:
  - Home: 'index.md'
  - Installation:
    - Docker: 'deploy/docker.md'
  - Environment: 'environment.md'
