site_name: goshorly docs
site_url: https://phil.mekelek.de/goshorly
repo_url: https://git.ucode.space/Phil/goshorly
site_dir: public
theme:
  name: material
  locale: en
  highlightjs: true

nav:
  - Home: 'index.md'
  - Installation:
    - Docker: 'deploy/docker.md'
    - Binary: 'deploy/binary.md'
  - Environment: 'environment.md'
